export const cardList = [
  {
    id: 1,
    theme: 'Web Design',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Без статуса',
    color: 'orange',
  },
  {
    id: 2,
    theme: 'Research',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Нужно сделать',
    color: 'green',
  },
  {
    id: 3,
    theme: 'Copywriting',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'В работе',
    color: 'purple',
  },
  {
    id: 4,
    theme: 'Web Design',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Тестирование',
    color: 'orange',
  },
  {
    id: 5,
    theme: 'Copywriting',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Готово',
    color: 'purple',
  },
]
